import { Metadata } from "next"

export default function Chat() {
    return (
        <main className='bg-blue-500 p-10'>
            <h1>Hello Chat</h1>
        </main>
    )
}

export const metadata: Metadata = {
    title: 'Chat',
    // description: 'Generated by create next app',
  }
